=== NightmareZ/FlowchartBuilder/Makarov.FlowchartBuilder/Translations/Translations.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Translations"
    targetNamespace="http://flowchartbuilder.blogspot.com"
    elementFormDefault="qualified"
    xmlns="http://flowchartbuilder.blogspot.com"
    xmlns:mstns="http://flowchartbuilder.blogspot.com"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:element name="Translation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Word" maxOccurs="unbounded">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="Key" type="xs:string" />
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Language" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NightmareZ/FlowchartBuilder/Makarov.FlowchartBuilder/Translations/English.xml
<?xml version="1.0" encoding="utf-8" ?>
<fb:Translation Language="English" xmlns:fb="http://flowchartbuilder.blogspot.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://flowchartbuilder.blogspot.com Translations.xsd">

  <fb:Word Key="FlowchartBuilder_Caption">FlowchartBuilder</fb:Word>

  <fb:Word Key="Menu_File">File</fb:Word>
  <fb:Word Key="Command_New">New...</fb:Word>
  <fb:Word Key="Command_Open">Open...</fb:Word>
  <fb:Word Key="Command_ExportImage">Export Image...</fb:Word>
  <fb:Word Key="Command_Save">Save</fb:Word>
  <fb:Word Key="Command_SaveAll">Save All</fb:Word>
  <fb:Word Key="Command_Close">Close</fb:Word>
  <fb:Word Key="Command_CloseAll">Close All</fb:Word>
  <fb:Word Key="Command_PageSetup">Page Setup</fb:Word>
  <fb:Word Key="Command_Print">Print</fb:Word>
  <fb:Word Key="Command_Exit">Exit</fb:Word>

  <fb:Word Key="Menu_Debug">Debug</fb:Word>
  <fb:Word Key="Command_ForceGarbageCollection">Force Garbage Collection</fb:Word>
  <fb:Word Key="Command_ForceFullGarbageCollection">Force Full Garbage Collection</fb:Word>
  
  <fb:Word Key="Menu_Edit">Edit</fb:Word>
  <fb:Word Key="Command_Undo">Undo</fb:Word>
  <fb:Word Key="Command_Redo">Redo</fb:Word>
  <fb:Word Key="Command_Cut">Cut</fb:Word>
  <fb:Word Key="Command_Copy">Copy</fb:Word>
  <fb:Word Key="Command_Paste">Paste</fb:Word>
  <fb:Word Key="Command_Delete">Delete</fb:Word>
  <fb:Word Key="Command_SelectAll">Select All</fb:Word>
  <fb:Word Key="Command_Deselect">Deselect</fb:Word>
  <fb:Word Key="Command_FixSelected">Lock Selected</fb:Word>
  <fb:Word Key="Command_FixAll">Lock All</fb:Word>
  <fb:Word Key="Command_UnfixAll">Unlock All</fb:Word>

  <fb:Word Key="Command_Group">Group</fb:Word>
  <fb:Word Key="Command_Ungroup">Ungroup</fb:Word>

  <fb:Word Key="Menu_Align">Align</fb:Word>
  <fb:Word Key="Command_AlignLeft">Align Left</fb:Word>
  <fb:Word Key="Command_AlignRight">Align Right</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontal">Align Center (Horizontal)</fb:Word>
  <fb:Word Key="Command_AlignCenterVertical">Align Center (Vertical)</fb:Word>
  <fb:Word Key="Command_AlignTop">Align Top</fb:Word>
  <fb:Word Key="Command_AlignBottom">Align Bottom</fb:Word>

  <fb:Word Key="Menu_AlignOnSheet">Align On Sheet</fb:Word>
  <fb:Word Key="Command_AlignLeftSheet">Align Left on Sheet</fb:Word>
  <fb:Word Key="Command_AlignRightSheet">Align Right on Sheet</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontalSheet">Align Center (Horizontal) on Sheet</fb:Word>
  <fb:Word Key="Command_AlignCenterVerticalSheet">Align Center (Vertical) on Sheet</fb:Word>
  <fb:Word Key="Command_AlignTopSheet">Align Top on Sheet</fb:Word>
  <fb:Word Key="Command_AlignBottomSheet">Align Bottom on Sheet</fb:Word>
  
  <fb:Word Key="Menu_View">View</fb:Word>
  <fb:Word Key="Command_ZoomIn">Zoom In</fb:Word>
  <fb:Word Key="Command_ZoomOut">Zoom Out</fb:Word>
  <fb:Word Key="Command_ZoomToWindow">Zoom To Window</fb:Word>
  <fb:Word Key="Command_ActualSize">Actual Size</fb:Word>
  <fb:Word Key="Command_Zoom">Zoom</fb:Word>
  <fb:Word Key="400%">400%</fb:Word>
  <fb:Word Key="200%">200%</fb:Word>
  <fb:Word Key="150%">150%</fb:Word>
  <fb:Word Key="125%">125%</fb:Word>
  <fb:Word Key="100%">100%</fb:Word>
  <fb:Word Key="75%">75%</fb:Word>
  <fb:Word Key="50%">50%</fb:Word>
  <fb:Word Key="25%">25%</fb:Word>
  <fb:Word Key="Command_Grid">Grid</fb:Word>
  <fb:Word Key="Command_Rulers">Rulers</fb:Word>
  <fb:Word Key="Command_SizeLocationLabel">Size and Location Label</fb:Word>
  <fb:Word Key="Command_PaletteWindow">Glyphs</fb:Word>
  <fb:Word Key="Command_PropertiesWindow">Properties</fb:Word>

  <fb:Word Key="Menu_Tools">Tools</fb:Word>

  <fb:Word Key="Menu_Window">Window</fb:Word>
  <fb:Word Key="Command_ResetWindowLocations">Reset Window Locations</fb:Word>

  <fb:Word Key="Menu_Settings">Settings</fb:Word>
  <fb:Word Key="Command_Languages">Languages</fb:Word>
  <fb:Word Key="Command_UnitsOfMeasurement">Units of Measurement</fb:Word>
  <fb:Word Key="Command_OtherSettings">Other Settings...</fb:Word>
  <fb:Word Key="Menu_ManageSettings">Manage Settings</fb:Word>
  <fb:Word Key="Command_LoadSettings">Load Settings...</fb:Word>
  <fb:Word Key="Command_SaveSettings">Save Settings...</fb:Word>

  <fb:Word Key="Menu_Help">Help</fb:Word>
  <fb:Word Key="Command_HelpTopics">Help Topics</fb:Word>
  <fb:Word Key="Command_About">About</fb:Word>

  <fb:Word Key="Wnd_About_Title">About Makarov Flowchart Builder</fb:Word>
  <fb:Word Key="Wnd_About_VersionLabel">FlowchartBuilder v</fb:Word>
  <fb:Word Key="Wnd_About_CopyrightLabel">Copyright © 2011 Makarov Michael. All Rights Reserved.</fb:Word>

  <fb:Word Key="Wnd_Palette_Title">Glyphs</fb:Word>
  <fb:Word Key="Wnd_Properties_Title">Properties</fb:Word>
  <fb:Word Key="Wnd_OtherSettings">Settings</fb:Word>

  <fb:Word Key="Tab_Common">Common</fb:Word>
  <fb:Word Key="Cb_LimitedHistory">Limited history</fb:Word>
  <fb:Word Key="Cb_CacheResources">Cache resources</fb:Word>
  <fb:Word Key="Cb_CacheImages">Cache images</fb:Word>
  <fb:Word Key="Cb_Antialiasing">Antialiasing</fb:Word>

  <fb:Word Key="Centimeters">Centimeters</fb:Word>
  <fb:Word Key="Foots">Foots</fb:Word>
  <fb:Word Key="Inches">Inches</fb:Word>
  <fb:Word Key="Millimeters">Millimeters</fb:Word>

  <fb:Word Key="mm">mm</fb:Word>
  <fb:Word Key="cm">cm</fb:Word>
  <fb:Word Key="inch">inch</fb:Word>
  <fb:Word Key="ft">ft</fb:Word>

  <fb:Word Key="width">width</fb:Word>
  <fb:Word Key="height">height</fb:Word>

  <fb:Word Key="OK">OK</fb:Word>
  <fb:Word Key="Cancel">Cancel</fb:Word>
  <fb:Word Key="Close">Close</fb:Word>
  <fb:Word Key="License_Text">Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under tha law.</fb:Word>

  <fb:Word Key="Msg_Error">Error</fb:Word>
  <fb:Word Key="Msg_Warning">Warning</fb:Word>
  <fb:Word Key="Msg_Info">Information</fb:Word>
  <fb:Word Key="Msg_InvalidImageExtension">Invalid image file extension.</fb:Word>
  <fb:Word Key="Msg_FunctionDisabledInNonRegisteredProgram">This function disabled in non registered program.</fb:Word>
  <fb:Word Key="Msg_Need_Restart_Application">Please, restart application.</fb:Word>

  <fb:Word Key="UndefinedGlyphName">*undefined*</fb:Word>
  <fb:Word Key="UndefinedGlyphFamily">Other</fb:Word>
  <fb:Word Key="UndefinedSheetName">*undefined*</fb:Word>
  <fb:Word Key="UndefinedSheetFamily">Other</fb:Word>

  <fb:Word Key="English">English</fb:Word>
  <fb:Word Key="Russian">Russian</fb:Word>
  <fb:Word Key="Ukrainian">Ukrainian</fb:Word>
</fb:Translation>

=== NightmareZ/FlowchartBuilder/Makarov.FlowchartBuilder/Translations/Ukrainian.xml
<?xml version="1.0" encoding="utf-8" ?>
<fb:Translation Language="Ukrainian" xmlns:fb="http://flowchartbuilder.blogspot.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://flowchartbuilder.blogspot.com Translations.xsd">

  <fb:Word Key="FlowchartBuilder_Caption">Редактор діаграм</fb:Word>

  <fb:Word Key="Menu_File">Файл</fb:Word>
  <fb:Word Key="Command_New">Новий...</fb:Word>
  <fb:Word Key="Command_Open">Відчинити...</fb:Word>
  <fb:Word Key="Command_ExportImage">Создати зображення...</fb:Word>
  <fb:Word Key="Command_Save">Сохранити</fb:Word>
  <fb:Word Key="Command_SaveAll">Сохранити усе</fb:Word>
  <fb:Word Key="Command_Close">Зачінити</fb:Word>
  <fb:Word Key="Command_CloseAll">Зачінити усе</fb:Word>
  <fb:Word Key="Command_PageSetup">Налаштунки друку</fb:Word>
  <fb:Word Key="Command_Print">Друк</fb:Word>
  <fb:Word Key="Command_Exit">Вихід</fb:Word>

  <fb:Word Key="Menu_Debug">Налагодження</fb:Word>
  <fb:Word Key="Command_ForceGarbageCollection">Ініціювати збірку сміття</fb:Word>
  <fb:Word Key="Command_ForceFullGarbageCollection">Ініціювати збірку сміття у всіх поколіннях</fb:Word>

  <fb:Word Key="Menu_Edit">Редагувати</fb:Word>
  <fb:Word Key="Command_Undo">Взад</fb:Word>
  <fb:Word Key="Command_Redo">Вперед</fb:Word>
  <fb:Word Key="Command_Cut">Вирізати</fb:Word>
  <fb:Word Key="Command_Copy">Копіювати</fb:Word>
  <fb:Word Key="Command_Paste">Вставити</fb:Word>
  <fb:Word Key="Command_Delete">Видалити</fb:Word>
  <fb:Word Key="Command_SelectAll">Виділити все</fb:Word>
  <fb:Word Key="Command_Deselect">Відмінити виділення</fb:Word>
  <fb:Word Key="Command_FixSelected">Закріпити виділене</fb:Word>
  <fb:Word Key="Command_FixAll">Закріпити все</fb:Word>
  <fb:Word Key="Command_UnfixAll">Відмините закріплення</fb:Word>

  <fb:Word Key="Command_Group">Створити групу</fb:Word>
  <fb:Word Key="Command_Ungroup">Розгрупувати</fb:Word>

  <fb:Word Key="Menu_Align">Вирівняти</fb:Word>
  <fb:Word Key="Command_AlignLeft">Вирівняти по лівому краю</fb:Word>
  <fb:Word Key="Command_AlignRight">Вирівняти по правому краю</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontal">Вирівняти по центру (горизонтально)</fb:Word>
  <fb:Word Key="Command_AlignCenterVertical">Вирівняти по центру (вертикально)</fb:Word>
  <fb:Word Key="Command_AlignTop">Вирівняти по верхньому краю</fb:Word>
  <fb:Word Key="Command_AlignBottom">Вирівняти по нижньому краю</fb:Word>

  <fb:Word Key="Menu_AlignOnSheet">Вирівняти по аркушу</fb:Word>
  <fb:Word Key="Command_AlignLeftSheet">Вирівняти по лівому краю аркуша</fb:Word>
  <fb:Word Key="Command_AlignRightSheet">Вирівняти по правому краю аркуша</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontalSheet">Вирівняти по центру аркуша (горизонтально)</fb:Word>
  <fb:Word Key="Command_AlignCenterVerticalSheet">Вирівняти по центру аркуша (вертикально)</fb:Word>
  <fb:Word Key="Command_AlignTopSheet">Вирівняти по верхньому краю аркуша</fb:Word>
  <fb:Word Key="Command_AlignBottomSheet">Вирівняти по нижньому краю аркуша</fb:Word>

  <fb:Word Key="Menu_View">Вид</fb:Word>
  <fb:Word Key="Command_ZoomIn">Збільшити</fb:Word>
  <fb:Word Key="Command_ZoomOut">Зменьшити</fb:Word>
  <fb:Word Key="Command_ZoomToWindow">Збільшити до размірів вікна</fb:Word>
  <fb:Word Key="Command_ActualSize">Оптимальний розмір</fb:Word>
  <fb:Word Key="Command_Zoom">Масштаб</fb:Word>
  <fb:Word Key="400%">400%</fb:Word>
  <fb:Word Key="200%">200%</fb:Word>
  <fb:Word Key="150%">150%</fb:Word>
  <fb:Word Key="125%">125%</fb:Word>
  <fb:Word Key="100%">100%</fb:Word>
  <fb:Word Key="75%">75%</fb:Word>
  <fb:Word Key="50%">50%</fb:Word>
  <fb:Word Key="25%">25%</fb:Word>
  <fb:Word Key="Command_Grid">Сітка</fb:Word>
  <fb:Word Key="Command_Rulers">Лінійки</fb:Word>
  <fb:Word Key="Command_SizeLocationLabel">Відібражати розмір и координати</fb:Word>
  <fb:Word Key="Command_PaletteWindow">Палітра</fb:Word>
  <fb:Word Key="Command_PropertiesWindow">Властивості</fb:Word>

  <fb:Word Key="Menu_Tools">Iнструменти</fb:Word>

  <fb:Word Key="Menu_Window">Вікно</fb:Word>
  <fb:Word Key="Command_ResetWindowLocations">Стандартне расположення вікон</fb:Word>

  <fb:Word Key="Menu_Settings">Налаштування</fb:Word>
  <fb:Word Key="Command_Languages">Мови</fb:Word>
  <fb:Word Key="Command_UnitsOfMeasurement">Одиниці вимірювання</fb:Word>
  <fb:Word Key="Command_OtherSettings">Iнші налаштунки...</fb:Word>

  <fb:Word Key="Menu_Help">Допомога</fb:Word>
  <fb:Word Key="Command_HelpTopics">Заголовки допомоги</fb:Word>
  <fb:Word Key="Command_About">Про програму</fb:Word>

  <fb:Word Key="Wnd_About_Title">Про Редактор Діаграм</fb:Word>
  <fb:Word Key="Wnd_About_VersionLabel">Версія:</fb:Word>
  <fb:Word Key="Wnd_About_CopyrightLabel">(c) 2011 Макаров Михайло.</fb:Word>

  <fb:Word Key="Wnd_Palette_Title">Палітра</fb:Word>
  <fb:Word Key="Wnd_Properties_Title">Властивості</fb:Word>
  <fb:Word Key="Wnd_OtherSettings">Налаштунки</fb:Word>
  <fb:Word Key="Menu_ManageSettings">Управління настройками</fb:Word>
  <fb:Word Key="Command_LoadSettings">Заватажити настройки...</fb:Word>
  <fb:Word Key="Command_SaveSettings">Сохранити настройки...</fb:Word>

  <fb:Word Key="Tab_Common">Загальні</fb:Word>
  <fb:Word Key="Cb_LimitedHistory">Обмеження історії</fb:Word>
  <fb:Word Key="Cb_CacheResources">Кешувати ресурси</fb:Word>
  <fb:Word Key="Cb_CacheImages">Кешувати зображення</fb:Word>
  <fb:Word Key="Cb_Antialiasing">Згладжування</fb:Word>

  <fb:Word Key="Centimeters">Сантиметри</fb:Word>
  <fb:Word Key="Foots">Фути</fb:Word>
  <fb:Word Key="Inches">Дюйми</fb:Word>
  <fb:Word Key="Millimeters">Міліметри</fb:Word>

  <fb:Word Key="mm">мм</fb:Word>
  <fb:Word Key="cm">см</fb:Word>
  <fb:Word Key="inch">дюйми</fb:Word>
  <fb:Word Key="ft">фути</fb:Word>

  <fb:Word Key="width">ширина</fb:Word>
  <fb:Word Key="height">висота</fb:Word>

  <fb:Word Key="OK">Примінити</fb:Word>
  <fb:Word Key="Cancel">Відміна</fb:Word>
  <fb:Word Key="Close">Зачінити</fb:Word>
  <fb:Word Key="License_Text">Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under tha law.</fb:Word>

  <fb:Word Key="Msg_Error">Помилка</fb:Word>
  <fb:Word Key="Msg_Warning">Увага</fb:Word>
  <fb:Word Key="Msg_Info">Інформація</fb:Word>
  <fb:Word Key="Msg_InvalidImageExtension">Некоріктне розширення графічного файла.</fb:Word>
  <fb:Word Key="Msg_FunctionDisabledInNonRegisteredProgram">Ця функція недоступна в незарегістрованій версії програми.</fb:Word>
  <fb:Word Key="Msg_Need_Restart_Application">Будьласка, перезавантажте програму.</fb:Word>

  <fb:Word Key="UndefinedGlyphName">*безіменний*</fb:Word>
  <fb:Word Key="UndefinedGlyphFamily">Інші</fb:Word>
  <fb:Word Key="UndefinedSheetName">*безіменний*</fb:Word>
  <fb:Word Key="UndefinedSheetFamily">Інші</fb:Word>

  <fb:Word Key="English">Англійська</fb:Word>
  <fb:Word Key="Russian">Російська</fb:Word>
  <fb:Word Key="Ukrainian">Українська</fb:Word>
</fb:Translation>

=== NightmareZ/FlowchartBuilder/Makarov.FlowchartBuilder/Translations/Russian.xml
<?xml version="1.0" encoding="utf-8" ?>
<fb:Translation Language="Russian" xmlns:fb="http://flowchartbuilder.blogspot.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://flowchartbuilder.blogspot.com Translations.xsd">

  <fb:Word Key="FlowchartBuilder_Caption">Редактор Диаграмм</fb:Word>

  <fb:Word Key="Menu_File">Файл</fb:Word>
  <fb:Word Key="Command_New">Новый...</fb:Word>
  <fb:Word Key="Command_Open">Открыть...</fb:Word>
  <fb:Word Key="Command_ExportImage">Экспортировать изображение...</fb:Word>
  <fb:Word Key="Command_Save">Сохранить</fb:Word>
  <fb:Word Key="Command_SaveAll">Сохранить всё</fb:Word>
  <fb:Word Key="Command_Close">Закрыть</fb:Word>
  <fb:Word Key="Command_CloseAll">Закрыть всё</fb:Word>
  <fb:Word Key="Command_PageSetup">Настройка печати</fb:Word>
  <fb:Word Key="Command_Print">Печать</fb:Word>
  <fb:Word Key="Command_Exit">Выход</fb:Word>

  <fb:Word Key="Menu_Debug">Отладка</fb:Word>
  <fb:Word Key="Command_ForceGarbageCollection">Инициировать сборку мусора</fb:Word>
  <fb:Word Key="Command_ForceFullGarbageCollection">Инициировать сборку мусора во всех поколениях</fb:Word>

  <fb:Word Key="Menu_Edit">Редактировать</fb:Word>
  <fb:Word Key="Command_Undo">Назад</fb:Word>
  <fb:Word Key="Command_Redo">Вперёд</fb:Word>
  <fb:Word Key="Command_Cut">Вырезать</fb:Word>
  <fb:Word Key="Command_Copy">Копировать</fb:Word>
  <fb:Word Key="Command_Paste">Вставить</fb:Word>
  <fb:Word Key="Command_Delete">Удалить</fb:Word>
  <fb:Word Key="Command_SelectAll">Выделить всё</fb:Word>
  <fb:Word Key="Command_Deselect">Убрать выделение</fb:Word>
  <fb:Word Key="Command_FixSelected">Закрепить выделенное</fb:Word>
  <fb:Word Key="Command_FixAll">Закрепить всё</fb:Word>
  <fb:Word Key="Command_UnfixAll">Убрать закрепление</fb:Word>

  <fb:Word Key="Command_Group">Создать группу</fb:Word>
  <fb:Word Key="Command_Ungroup">Разгруппировать</fb:Word>

  <fb:Word Key="Menu_Align">Выровнять</fb:Word>
  <fb:Word Key="Command_AlignLeft">Выровнять по левому краю</fb:Word>
  <fb:Word Key="Command_AlignRight">Выровнять по правому краю</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontal">Выровнять по центру (горизонтально)</fb:Word>
  <fb:Word Key="Command_AlignCenterVertical">Выровнять по центру (вертикально)</fb:Word>
  <fb:Word Key="Command_AlignTop">Выровнять по верхнему краю</fb:Word>
  <fb:Word Key="Command_AlignBottom">Выровнять по нижнему краю</fb:Word>

  <fb:Word Key="Menu_AlignOnSheet">Выровнять по листу</fb:Word>
  <fb:Word Key="Command_AlignLeftSheet">Выровнять по левому краю листа</fb:Word>
  <fb:Word Key="Command_AlignRightSheet">Выровнять по правому краю листа</fb:Word>
  <fb:Word Key="Command_AlignCenterHorizontalSheet">Выровнять по центру листа (горизонтально)</fb:Word>
  <fb:Word Key="Command_AlignCenterVerticalSheet">Выровнять по центру листа (вертикально)</fb:Word>
  <fb:Word Key="Command_AlignTopSheet">Выровнять по верхнему краю листа</fb:Word>
  <fb:Word Key="Command_AlignBottomSheet">Выровнять по нижнему краю листа</fb:Word>

  <fb:Word Key="Menu_View">Вид</fb:Word>
  <fb:Word Key="Command_ZoomIn">Увеличить</fb:Word>
  <fb:Word Key="Command_ZoomOut">Уменьшить</fb:Word>
  <fb:Word Key="Command_ZoomToWindow">Увеличить до размеров окна</fb:Word>
  <fb:Word Key="Command_ActualSize">Удобный размер</fb:Word>
  <fb:Word Key="Command_Zoom">Масштаб</fb:Word>
  <fb:Word Key="400%">400%</fb:Word>
  <fb:Word Key="200%">200%</fb:Word>
  <fb:Word Key="150%">150%</fb:Word>
  <fb:Word Key="125%">125%</fb:Word>
  <fb:Word Key="100%">100%</fb:Word>
  <fb:Word Key="75%">75%</fb:Word>
  <fb:Word Key="50%">50%</fb:Word>
  <fb:Word Key="25%">25%</fb:Word>
  <fb:Word Key="Command_Grid">Сетка</fb:Word>
  <fb:Word Key="Command_Rulers">Линейки</fb:Word>
  <fb:Word Key="Command_SizeLocationLabel">Отображать размер и координаты</fb:Word>
  <fb:Word Key="Command_PaletteWindow">Палитра</fb:Word>
  <fb:Word Key="Command_PropertiesWindow">Свойства</fb:Word>

  <fb:Word Key="Menu_Tools">Инструменты</fb:Word>

  <fb:Word Key="Menu_Window">Окно</fb:Word>
  <fb:Word Key="Command_ResetWindowLocations">Стандартное расположение окон</fb:Word>

  <fb:Word Key="Menu_Settings">Настройки</fb:Word>
  <fb:Word Key="Command_Languages">Языки</fb:Word>
  <fb:Word Key="Command_UnitsOfMeasurement">Единицы измерения</fb:Word>
  <fb:Word Key="Command_OtherSettings">Другие настройки...</fb:Word>
  <fb:Word Key="Menu_ManageSettings">Управление настройками</fb:Word>
  <fb:Word Key="Command_LoadSettings">Загрузить настройки...</fb:Word>
  <fb:Word Key="Command_SaveSettings">Сохранить настройки...</fb:Word>

  <fb:Word Key="Menu_Help">Помощь</fb:Word>
  <fb:Word Key="Command_HelpTopics">Оглавление помощи</fb:Word>
  <fb:Word Key="Command_About">О программе</fb:Word>

  <fb:Word Key="Wnd_About_Title">О Редакторе Диаграмм</fb:Word>
  <fb:Word Key="Wnd_About_VersionLabel">Версия:</fb:Word>
  <fb:Word Key="Wnd_About_CopyrightLabel">(c) 2011 Макаров Михаил.</fb:Word>

  <fb:Word Key="Wnd_Palette_Title">Палитра</fb:Word>
  <fb:Word Key="Wnd_Properties_Title">Свойства</fb:Word>
  <fb:Word Key="Wnd_OtherSettings">Настройки</fb:Word>

  <fb:Word Key="Tab_Common">Общие</fb:Word>
  <fb:Word Key="Cb_LimitedHistory">Ограничение истории</fb:Word>
  <fb:Word Key="Cb_CacheResources">Кэшировать ресурсы</fb:Word>
  <fb:Word Key="Cb_CacheImages">Кэшировать изображения</fb:Word>
  <fb:Word Key="Cb_Antialiasing">Сглаживание</fb:Word>

  <fb:Word Key="Centimeters">Сантиметры</fb:Word>
  <fb:Word Key="Foots">Футы</fb:Word>
  <fb:Word Key="Inches">Дюймы</fb:Word>
  <fb:Word Key="Millimeters">Миллиметры</fb:Word>

  <fb:Word Key="mm">мм</fb:Word>
  <fb:Word Key="cm">см</fb:Word>
  <fb:Word Key="inch">дюймов</fb:Word>
  <fb:Word Key="ft">футов</fb:Word>

  <fb:Word Key="width">ширина</fb:Word>
  <fb:Word Key="height">высота</fb:Word>

  <fb:Word Key="OK">Применить</fb:Word>
  <fb:Word Key="Cancel">Отмена</fb:Word>
  <fb:Word Key="Close">Закрыть</fb:Word>
  <fb:Word Key="License_Text">Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under tha law.</fb:Word>

  <fb:Word Key="Msg_Error">Ошибка</fb:Word>
  <fb:Word Key="Msg_Warning">Внимание</fb:Word>
  <fb:Word Key="Msg_Info">Информация</fb:Word>
  <fb:Word Key="Msg_InvalidImageExtension">Неправильное расширение графического файла.</fb:Word>
  <fb:Word Key="Msg_FunctionDisabledInNonRegisteredProgram">Эта функция недоступна в незарегистрированной версии программы.</fb:Word>
  <fb:Word Key="Msg_Need_Restart_Application">Пожалуйста, перезапустите программу.</fb:Word>

  <fb:Word Key="UndefinedGlyphName">*безымянный*</fb:Word>
  <fb:Word Key="UndefinedGlyphFamily">Другие</fb:Word>
  <fb:Word Key="UndefinedSheetName">*безымянный*</fb:Word>
  <fb:Word Key="UndefinedSheetFamily">Другие</fb:Word>
  
  <fb:Word Key="English">Английский</fb:Word>
  <fb:Word Key="Russian">Русский</fb:Word>
  <fb:Word Key="Ukrainian">Украинский</fb:Word>
</fb:Translation>
